### ISSUE TITLE
Add docker-compose instructions

### ISSUE THREAD

**Issue by dcramer** [getsentry/spotlight#653]
Easy way to utilize the sidecar in a random project is just adding it to a docker-compose.yml.

We should add a simple snippet for that so folks can copypasta.

e.g.

```yaml
version: "3.7"
services:
  spotlight:
    image: ghcr.io/getsentry/spotlight:latest
    restart: on-failure
    ports:
      - "8969:8969"
```
